Fix watchable tests
joan38/kubernetes-client pull request #141
Opened 2022-06-24 05:19 UTC by petern-sc

Currently the watchable tests don't run because `(IO[Unit], IO[Unit]).parSequence => IO[(IO[Unit], Unit)]`. Change to List to parSequence works as intended

Correct watch events logic to make the tests pass

2022-06-24 05:21 UTC, petern-sc commented
@joan38 don't seem to be able to request review via the github UI, if you get a chance 🙏

2022-06-25 00:19 UTC, remibesse commented
I'll be looking into this. Thanks @petern-sc

2022-07-08 00:40 UTC, joan38 requested changes

2022-07-08 00:40 UTC, joan38 commented on kubernetes-client/test/src/com/goyeau/kubernetes/client/operation/WatchableTests.scala
>        ).parSequence
I think that would be better if it stays as a tuple and that `parSequence` needs to be `parTupled`.

2022-07-08 00:40 UTC, joan38 commented on kubernetes-client/test/src/com/goyeau/kubernetes/client/operation/WatchableTests.scala
>        ).parSequence
Same as above:
I think that would be better if it stays as a tuple and that `parSequence` needs to be `parTupled`.

2022-07-08 01:36 UTC, merged