switch to http4s jdk client for Pod exec
joan38/kubernetes-client pull request #20
Opened 2020-05-13 07:16 UTC by novakov-alexey

Here is a PR to switch to http4s jdk client to perform Pod exec. This removes akka-http dependecy.

One caveat: http4s-jdk client requires JDK11, so that our kubernetes-client will require Java 11 or higher. I think it is fair requirement, since JDK11 became default version for production today.

2020-05-13 17:03 UTC, novakov-alexey commented on build.sc
> +    def testOne(args: String*) = T.command {
this allows to run a single scalatest case via:
```bash
mill kubernetes-client"[2.13.2]".test.testOne "com.goyeau.kubernetes.client.api.PodsApiTest"
```

2020-05-13 17:05 UTC, novakov-alexey commented on kubernetes-client/src/com/goyeau/kubernetes/client/api/PodsApi.scala
> +      flow: ExecStream => T,
I am not sure how user would like to consume server messages. This flow function should allow user to capture message via Monoid, potentially discarding some them or converting into string. 🤔

2020-05-13 18:01 UTC, joan38 commented
I think it's ok to require JDK 11.
For some reason CI is not picking up the last commit, do you mind squashing all commits into 1 and force pushing to see if it picks it up?

2020-05-13 18:14 UTC, novakov-alexey commented
Just pushed a couple of times, CI job is not starting. Not sure if it is GitHub problem or not.

2020-05-13 18:25 UTC, novakov-alexey commented
🤣 it is my issue. CI yaml file had mistakes and this was only visible in flow file view from Actions tab

2020-05-14 09:48 UTC, novakov-alexey commented
@joan38 so everything seems fine now. CI succeeded.

2020-05-15 07:59 UTC, joan38 commented
Thanks @novakov-alexey. Bare with me, I'll review this this weekend.

2020-05-19 18:07 UTC, joan38 requested changes

2020-05-19 18:07 UTC, joan38 commented on kubernetes-client/src/com/goyeau/kubernetes/client/api/PodsApi.scala
> +final case class StdErr(data: String) extends ExecStream
Can we wrap the case classes in an `object ExecStream`?
Also should we add `def data: String` on `ExecStream` so that the user does not have to match if it wants all data independently from the output stream.

2020-05-19 18:07 UTC, joan38 commented on kubernetes-client/src/com/goyeau/kubernetes/client/api/PodsApi.scala
> +      flow: ExecStream => T,
Sounds good to me

2020-05-19 20:00 UTC, novakov-alexey commented on kubernetes-client/src/com/goyeau/kubernetes/client/api/PodsApi.scala
> +final case class StdErr(data: String) extends ExecStream
Done

2020-05-19 21:08 UTC, joan38 approved these changes
Thanks that's awesome

2020-05-19 21:09 UTC, merged