bugfix: refresh before token expires, not after
joan38/kubernetes-client pull request #254
Opened 2023-11-15 07:30 UTC by timbertson

If you set `refreshBeforeExpiration` to 1 minute, the current code refreshes the token only _after_ the token has expired for at least a minute. Time maths are hard, I had to add the test to actually verify my hunch 😆

2023-11-15 14:24 UTC, joan38 approved these changes

2023-11-15 15:13 UTC, joan38 commented
`./mill __.style`, push the style fix and we should be good to go.
Thanks!

2023-11-15 22:25 UTC, timbertson commented
Done 👍

2023-11-15 23:31 UTC, yurique commented
Oh interesting 🤔 
What a nasty bug and a nice catch! 

It indeed looks like a `plusSeconds` vs `minusSeconds` problem here:
```scala
val shouldRenew =  cached.expirationTimestamp.exists(_.isBefore(now.minusSeconds(refreshBeforeExpiration.toSeconds)))
                                                                     ~~~~~~~~ 
```

it should be like this (with `.plusSeconds`), right? (time maths are hard :) )
```

don't refresh
TIME ------------------------------------------------------------------->
               | now       | now+                        | token
                             refreshBefore                 expiration
                                 \------------------------NOT isBefore

do refresh
TIME ------------------------------------------------------------------->
               | now       | token                      | now+                        
                             expiration                   refreshBefore 
                                 isBefore---------------------/


do refresh
TIME ------------------------------------------------------------------->
              | token               | now               | now+                        
                expiration                                refreshBefore 
                   isBefore---------------------------------/ 
```

2023-11-15 23:31 UTC, yurique commented on kubernetes-client/test/src/com/goyeau/kubernetes/client/cache/AuthorizationCacheTest.scala
> +      cache    <- AuthorizationCache[IO](retrieve = auth, refreshBeforeExpiration = 10.seconds)
might be worth adding a "few" seconds to the `refreshBeforeExpiration` - in case the test takes more than 2 seconds to run for whatever reason

2023-11-15 23:35 UTC, yurique approved these changes

2023-11-17 20:18 UTC, joan38 requested changes

2023-11-17 20:18 UTC, joan38 commented on kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
Can we do `now.plus(refreshBeforeExpiration.toJava)` instead.

You'll need the `import scala.jdk.DurationConverters.*`

2023-11-17 20:18 UTC, joan38 commented on kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
@timbertson ☝🏼 in case you missed

2023-11-17 23:53 UTC, timbertson commented on kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
Cheers, done 👍

2023-11-18 00:24 UTC, yurique commented on kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
ouch,
```
Error:  /home/runner/work/kubernetes-client/kubernetes-client/kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala:8:18: object DurationConverters is not a member of package jdk
Error:  import scala.jdk.DurationConverters.*
```

I guess it's not available in scala 2.12

2023-11-24 06:28 UTC, joan38 commented on kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
We need: https://github.com/scala/scala-java8-compat
```
ivy"org.scala-lang.modules::scala-java8-compat:1.0.2"
```

2023-11-24 09:49 UTC, timbertson commented
Sorry I got waylaid, feel free to push whatever you need to my branch to
sort it out.

On Fri, 24 Nov 2023, 5:28 pm Joan Goyeau, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> <https://github.com/joan38/kubernetes-client/pull/254#discussion_r1403981578>
> :
>
> > @@ -38,8 +38,8 @@ object AuthorizationCache {
>                case Some(cached) =>
>                  F.realTimeInstant
>                    .flatMap { now =>
> -                    val shouldRenew =
> -                      cached.expirationTimestamp.exists(_.isBefore(now.minusSeconds(refreshBeforeExpiration.toSeconds)))
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
>
> We need: https://github.com/scala/scala-java8-compat
>
> ivy"org.scala-lang.modules::scala-java8-compat:1.0.2"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/joan38/kubernetes-client/pull/254#discussion_r1403981578>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAADOXCO67BLUGMO24IWNSTYGA5ANAVCNFSM6AAAAAA7MA6FT6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONBXGM3TCNRSGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-24 13:33 UTC, yurique commented on kubernetes-client/src/com/goyeau/kubernetes/client/util/cache/AuthorizationCache.scala
> +                    val minExpiry   = now.plusSeconds(refreshBeforeExpiration.toSeconds)
done

2023-11-24 23:23 UTC, joan38 approved these changes

2023-11-24 23:24 UTC, merged